### ISSUE TITLE
Login 

### ISSUE THREAD

**Issue by UmangPandav** [sgcuber24/attendance_system_app#2]
How to login in to this app.

**Comment by UmangPandav** [comment]
I think APIs are not working.

**Comment by gsriram24** [comment]
Please clone the repo, host the backend found in the links given in the readme, and you can change the URL and build the app for the APIs to work.

**Comment by gsriram24** [comment]
I have updated the readme with the backend and the admin panel. You can definitely clone them and work on them. And hey, you could also always contribute and make it more modular by contributing and adding these URLs in an env file.
